title: Hola, Soy Angel Sanchez Tenjo ðŸ”‹
email: ajsanchez22@gmail.com
description: <p><i>Un programador no nace, se hace y siempre estÃ¡ en continuo aprendizaje. âž¶ </i></p>
author: AngelSanchezT
baseurl: "/"
# url: "https://startbootstrap.github.io"

repository: AngelSanchezT/angelsanchezt.github.io

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
